package noctiluca.timeline.domain.usecase.json

import noctiluca.test.shared.URL_MASTODON_JP

val JSON_STATUSES_FAVOURITE = """
    {"id":"1","created_at":"2022-01-01T00:00:00.000Z","in_reply_to_id":null,"in_reply_to_account_id":null,"sensitive":false,"spoiler_text":"<p>warning text</p>","visibility":"public","language":"ja","uri":"$URL_MASTODON_JP/@piyo","url":"$URL_MASTODON_JP/@piyo/1","replies_count":0,"reblogs_count":0,"favourites_count":1,"favourited":true,"reblogged":false,"muted":false,"bookmarked":false,"content":"<p>toot content</p>","reblog":null,"account":{"id":"2","username":"piyo","acct":"piyo@mstdn.jp","display_name":"Kotori Otonashi","locked":false,"bot":false,"discoverable":false,"group":false,"created_at":"2020-01-01T00:00:00.000Z","note":"<p>content</p>","url":"$URL_MASTODON_JP/@piyo","avatar":"$URL_MASTODON_JP/accounts/avatars/avater.jpg","avatar_static":"$URL_MASTODON_JP/accounts/avatars/original/avater.jpg","header":"$URL_MASTODON_JP/accounts/headers/header.jpg","header_static":"$URL_MASTODON_JP/accounts/headers/header.jpg","followers_count":10,"following_count":10,"statuses_count":5,"last_status_at":"2022-01-01","emojis":[],"oauth_authentications":[],"fields":[]},"media_attachments":[],"mentions":[],"tags":[],"emojis":[],"card":null,"poll":null}
""".trim()

val JSON_STATUSES_UNFAVOURITE = """
    {"id":"1","created_at":"2022-01-01T00:00:00.000Z","in_reply_to_id":null,"in_reply_to_account_id":null,"sensitive":false,"spoiler_text":"<p>warning text</p>","visibility":"public","language":"ja","uri":"$URL_MASTODON_JP/@piyo","url":"$URL_MASTODON_JP/@piyo/1","replies_count":0,"reblogs_count":0,"favourites_count":0,"favourited":false,"reblogged":false,"muted":false,"bookmarked":false,"content":"<p>toot content</p>","reblog":null,"account":{"id":"2","username":"piyo","acct":"piyo@mstdn.jp","display_name":"Kotori Otonashi","locked":false,"bot":false,"discoverable":false,"group":false,"created_at":"2020-01-01T00:00:00.000Z","note":"<p>content</p>","url":"$URL_MASTODON_JP/@piyo","avatar":"$URL_MASTODON_JP/accounts/avatars/avater.jpg","avatar_static":"$URL_MASTODON_JP/accounts/avatars/original/avater.jpg","header":"$URL_MASTODON_JP/accounts/headers/header.jpg","header_static":"$URL_MASTODON_JP/accounts/headers/header.jpg","followers_count":10,"following_count":10,"statuses_count":5,"last_status_at":"2022-01-01","emojis":[],"oauth_authentications":[],"fields":[]},"media_attachments":[],"mentions":[],"tags":[],"emojis":[],"card":null,"poll":null}
""".trim()

val JSON_STATUSES_BOOKMARK = """
    {"id":"1","created_at":"2022-01-01T00:00:00.000Z","in_reply_to_id":null,"in_reply_to_account_id":null,"sensitive":false,"spoiler_text":"<p>warning text</p>","visibility":"public","language":"ja","uri":"$URL_MASTODON_JP/@piyo","url":"$URL_MASTODON_JP/@piyo/1","replies_count":0,"reblogs_count":0,"favourites_count":0,"favourited":false,"reblogged":false,"muted":false,"bookmarked":true,"content":"<p>toot content</p>","reblog":null,"account":{"id":"2","username":"piyo","acct":"piyo@mstdn.jp","display_name":"Kotori Otonashi","locked":false,"bot":false,"discoverable":false,"group":false,"created_at":"2020-01-01T00:00:00.000Z","note":"<p>content</p>","url":"$URL_MASTODON_JP/@piyo","avatar":"$URL_MASTODON_JP/accounts/avatars/avater.jpg","avatar_static":"$URL_MASTODON_JP/accounts/avatars/original/avater.jpg","header":"$URL_MASTODON_JP/accounts/headers/header.jpg","header_static":"$URL_MASTODON_JP/accounts/headers/header.jpg","followers_count":10,"following_count":10,"statuses_count":5,"last_status_at":"2022-01-01","emojis":[],"oauth_authentications":[],"fields":[]},"media_attachments":[],"mentions":[],"tags":[],"emojis":[],"card":null,"poll":null}
""".trim()

val JSON_STATUSES_UNBOOKMARK = """
    {"id":"1","created_at":"2022-01-01T00:00:00.000Z","in_reply_to_id":null,"in_reply_to_account_id":null,"sensitive":false,"spoiler_text":"<p>warning text</p>","visibility":"public","language":"ja","uri":"$URL_MASTODON_JP/@piyo","url":"$URL_MASTODON_JP/@piyo/1","replies_count":0,"reblogs_count":0,"favourites_count":0,"favourited":false,"reblogged":false,"muted":false,"bookmarked":false,"content":"<p>toot content</p>","reblog":null,"account":{"id":"2","username":"piyo","acct":"piyo@mstdn.jp","display_name":"Kotori Otonashi","locked":false,"bot":false,"discoverable":false,"group":false,"created_at":"2020-01-01T00:00:00.000Z","note":"<p>content</p>","url":"$URL_MASTODON_JP/@piyo","avatar":"$URL_MASTODON_JP/accounts/avatars/avater.jpg","avatar_static":"$URL_MASTODON_JP/accounts/avatars/original/avater.jpg","header":"$URL_MASTODON_JP/accounts/headers/header.jpg","header_static":"$URL_MASTODON_JP/accounts/headers/header.jpg","followers_count":10,"following_count":10,"statuses_count":5,"last_status_at":"2022-01-01","emojis":[],"oauth_authentications":[],"fields":[]},"media_attachments":[],"mentions":[],"tags":[],"emojis":[],"card":null,"poll":null}
""".trim()
