name: 'Run Unit Test'

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Prepare dummy access token
        run: echo instances.social.token=XXX > ./local.properties
      - name: Run test on Android
        run: ./gradlew testDebugUnitTest --stacktrace testDebugUnitTestReport --stacktrace
      - name: Publish test report on Android
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          check_name: 'Test Report on Android'
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
      - name: Run test on Desktop
        if: success() || failure()
        run: ./gradlew desktopTest --stacktrace desktopTestReport --stacktrace
      - name: Publish test report on Desktop
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          check_name: 'Test Report on Desktop'
          report_paths: '**/build/test-results/desktopTest/TEST-*.xml'
      - name: Archive test on Android results artifact
        uses: actions/upload-artifact@master
        if: success() || failure()
        with:
          name: all-android-test-reports
          path: ./build/reports/allTests/testDebugUnitTest
      - name: Archive test on Desktop results artifact
        uses: actions/upload-artifact@master
        if: success() || failure()
        with:
          name: all-desktop-test-reports
          path: ./build/reports/allTests/desktopTest
